apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::062324246978:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062324246978:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NWWMDBE0TXVK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-26T07:51:51Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-26T07:51:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1679"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4c60b3af-d7a3-4ded-a57a-9befcb3201e3
